group: deprecated-2017Q2
dist: trusty
sudo: required
language: java
jdk:
  - openjdk8
  - openjdk11
matrix:
  include:
    - name: "camunda 7.6.0 JDK 8"
      env: CAMUNDA_BPM_VERSION=7.6.0 CAMUNDA_COMMONS_VERSION=1.4.0 CAMUNDA_SPIN_VERSION=1.3.1 CAMUNDA_CONNECT_VERSION=1.0.4
      jdk: openjdk8
    - name: "camunda 7.7.0 JDK 8"
      env: CAMUNDA_BPM_VERSION=7.7.0 CAMUNDA_COMMONS_VERSION=1.4.0 CAMUNDA_SPIN_VERSION=1.3.1 CAMUNDA_CONNECT_VERSION=1.0.4
      jdk: openjdk8
    - name: "camunda 7.8.0 JDK 8"
      env: CAMUNDA_BPM_VERSION=7.8.0 CAMUNDA_COMMONS_VERSION=1.4.0 CAMUNDA_SPIN_VERSION=1.4.1 CAMUNDA_CONNECT_VERSION=1.0.5
      jdk: openjdk8
    - name: "camunda 7.9.0 JDK 8"
      env: CAMUNDA_BPM_VERSION=7.9.0 CAMUNDA_COMMONS_VERSION=1.5.0 CAMUNDA_SPIN_VERSION=1.5.1 CAMUNDA_CONNECT_VERSION=1.0.6
      jdk: openjdk8
    - name: "camunda 7.10.0 JDK 8"
      env: CAMUNDA_BPM_VERSION=7.10.0 CAMUNDA_COMMONS_VERSION=1.6.1 CAMUNDA_SPIN_VERSION=1.6.3 CAMUNDA_CONNECT_VERSION=1.1.0
      jdk: openjdk8
    - name: "camunda 7.11.0 JDK 8"
      env: CAMUNDA_BPM_VERSION=7.11.0 CAMUNDA_COMMONS_VERSION=1.6.1 CAMUNDA_SPIN_VERSION=1.6.7
      CAMUNDA_CONNECT_VERSION=1.1.4
      jdk: openjdk8
    - name: "camunda 7.6.0 JDK 11"
      env: CAMUNDA_BPM_VERSION=7.6.0 CAMUNDA_COMMONS_VERSION=1.4.0 CAMUNDA_SPIN_VERSION=1.3.1 CAMUNDA_CONNECT_VERSION=1.0.4
      jdk: openjdk11
    - name: "camunda 7.7.0 JDK 11"
      env: CAMUNDA_BPM_VERSION=7.7.0 CAMUNDA_COMMONS_VERSION=1.4.0 CAMUNDA_SPIN_VERSION=1.3.1 CAMUNDA_CONNECT_VERSION=1.0.4
      jdk: openjdk11
    - name: "camunda 7.8.0 JDK 11"
      env: CAMUNDA_BPM_VERSION=7.8.0 CAMUNDA_COMMONS_VERSION=1.4.0 CAMUNDA_SPIN_VERSION=1.4.1 CAMUNDA_CONNECT_VERSION=1.0.5
      jdk: openjdk11
    - name: "camunda 7.9.0 JDK 11"
      env: CAMUNDA_BPM_VERSION=7.9.0 CAMUNDA_COMMONS_VERSION=1.5.0 CAMUNDA_SPIN_VERSION=1.5.1 CAMUNDA_CONNECT_VERSION=1.0.6
      jdk: openjdk11
    - name: "camunda 7.10.0 JDK 11"
      env: CAMUNDA_BPM_VERSION=7.10.0 CAMUNDA_COMMONS_VERSION=1.6.1 CAMUNDA_SPIN_VERSION=1.6.3 CAMUNDA_CONNECT_VERSION=1.1.0
      jdk: openjdk11
    - name: "camunda 7.11.0 JDK 11"
      env: CAMUNDA_BPM_VERSION=7.11.0 CAMUNDA_COMMONS_VERSION=1.6.1 CAMUNDA_SPIN_VERSION=1.6.7 CAMUNDA_CONNECT_VERSION=1.1.4
      jdk: openjdk11
script: mvn install -P ci
